name: delivery-boss-cicd

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  CODE_DEPLOY_APP_NAME: ${{ secrets.CODE_DEPLOY_APP_NAME }}
  DEPLOYMENT_GROUP_NAME: ${{ secrets.DEPLOYMENT_GROUP_NAME }}
      
jobs:
  # CI
  test:
    runs-on: ubuntu-latest
    steps:
      # git actions를 트리거한 commit에 checkout
      - name: checkout commit
        uses: actions/checkout@v3
      
      # node 환경 세팅
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      # 환경 변수 세팅
      - name: setup environment variables
        run: |
          touch .env
          echo "DATABASE_URL = ${{ secrets.DATABASE_URL }}" >> .env
          echo "PORT = ${{ secrets.PORT }}" >> .env

      # 패키지 설치
      - name: setup packages
        run: npm install

      # 테스트 진행
      - name: start test
        run: npm test

  # CD
  delivery:
    # test가 성공해야 실행
    needs: test
    
    runs-on: ubuntu-latest
    steps:
      # git actions를 트리거한 commit에 checkout
      - name: checkout commit
        uses: actions/checkout@v3

      # S3에게 전달할 압축 파일 생성
      - name: make .zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .

      # AWS 서비스에 접근하기 위한 권한을 부여 받기
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      # S3로 압축 파일 업로드
      - name: upload .zip file to S3
        run: aws s3 cp ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
